### ISSUE TITLE
Incorrect requirements

### ISSUE THREAD

**Issue by 357up** [kristuff/abuseipdb#1]
Hi Chris,

First of all, thank you for your work developing this great library. 

I just wanted to point out, that according to the README, the library supports PHP 7.1, however, I could not get working versions starting from 0.9.8. Follwoing error was thrown:
`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Return value of Kristuff\\AbuseIPDB\\ApiResponse::getObject() must be an instance of Kristuff\\AbuseIPDB\\object or null, instance of stdClass returned in [..]/badbots/vendor/kristuff/abuseipdb/lib/ApiResponse.php:77\nStack trace:\n#0 [..]/badbots/lib/abuseIPDB.php(25): Kristuff\\AbuseIPDB\\ApiResponse->getObject()\n#1 [..]/badbots/check_rep.php(158): include('[..]...')\n#2 [..]/badbots/check_rep.php(200): check_blacklist('ip', '{REDACTED}')\n#3 {main}\n  thrown in [..]/badbots/vendor/kristuff/abuseipdb/lib/ApiResponse.php on line 77\n'`

I had to downgrade to version 0.9.7 in order to get it working on 7.1. 

It's probably naive to hope for backwards compatibility patches, but at least you could update the README in order to avoid confusion. Thank you!

**Comment by kristuff** [comment]
Hi,
Thanks for using this library and reporting this.

This is a bug introduced in version 0.9.8 with PHP strict types: the method `ApiResponse::getObject()` has an incorrect return type. 
I have changed the return type to `?\stdClass`,  tested only on 7.3 but should work with PHP 7.1 as well.

```php
   /**
     * @return \stdClass|null
     */
    public function getObject(): ?\stdClass
```
Would be great if you confirm the bug is fixed with latest realease (0.9.12).
Thanks for your feedback.

**Comment by 357up** [comment]
Wow, thank you for the extremely fast response and fix. I have tested version 0.9.12 with PHP 7.1 and the previously thrown error is gone and I get the expected output.

**Comment by kristuff** [comment]
You're welcome. Thank you for reporting and quick test :)
