### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by eydun** [kristuff/abuseipdb#2]
Thank you for building this awesome package.

For your info, I get this php notice, when checking a single ip:
```
PHP Notice: Undefined property: stdClass::$errors in /vendor/kristuff/abuseipdb/lib/ApiResponse.php:113
```

**Comment by kristuff** [comment]
Thanks for reporting this 👍
I was not checking properly if property exists and missed the PHP notice.
This has been fixed in 0.9.13.
