### ISSUE TITLE
Feature: set curl timeout

### ISSUE THREAD

**Issue by eydun** [kristuff/abuseipdb#3]
It would be nice if it was possible to set the curl timeout-limit.

**Comment by kristuff** [comment]
You are right, it would be a great feature when server is not responding like today.. 
I should implement this soon.

**Comment by kristuff** [comment]
Implemented in v0.9.14: the `ApiHandler` (and `QuietApiHandler`) constructor takes now a timeout in third parameter. The timeout is expressed in **milliseconds** .

API was already up but I was able to test it with small value (40 ms for connection, or 400 for a request that takes times)

```
<?php 

require realpath(__DIR__) .'/vendor/autoload.php';

$handler = new \Kristuff\AbuseIPDB\QuietApiHandler('munged',[], 400);

$query = $handler->check('127.0.0.1', 365, true); // verbose check on 365 days takes times...

if ($query->hasError()){
    foreach ($query->errors() as $err){
        echo "Error: " . $err->detail . "\n";
    }
    return;
}

echo $query->getPlaintext() . PHP_EOL;
```
> Error: Operation timed out after 400 milliseconds with 46107 bytes received

or 

> Error: Operation timed out after 40 milliseconds with 0 out of 0 bytes received

**Comment by eydun** [comment]
Thanks for the prompt solution!

**Comment by kristuff** [comment]
You're welcome. Also added  `ApiHandler::setTimeout(int $timeout)` method in latest release, to allow to change/reset timeout between requests.
