### ISSUE TITLE
Edge case in email regex pattern

### ISSUE THREAD

**Issue by AndisGrossteins** [kristuff/abuseipdb#4]
I was running some tests before deploying a custom blocking/reporting solution and found an edge case.

The [email address regex in `cleanMessage` method](https://github.com/kristuff/abuseipdb/blob/5639f1813a7be889c9028f722e9fe252bac34df1/lib/ApiHandler.php#L472) is too greedy and replaced timestamps in my log messages.

For example:
```log
WordPress login brute-force attempt @2022-10-04Z22:58:48.
``` 
After replacement resulted in:
```log
WordPress login brute-force attempt *
```

While I can avoid this issue by removing the dot or `@` from messages, there could be more edge cases like this with the current regex.
For one, you should avoid using asterisks since no part of a valid email address can be zero characters:
```php
$emailPattern = "/[^@\s]+@[^@\s]+\.[^@\s]+/";
```
That's still not perfect so I'd suggest using a simplified email regex with `\b` word boundary operator:
```php
$emailPattern = "/\b[A-Z0-9+_.-]+@[A-Z0-9.-]+\b/i";
```
That would also match local username addresses without TLD like `root@hostname-no-tld` and avoid matching beyond the address.

Here's a quick test case for the last regex on regex101: https://regex101.com/r/cgXSJo/1

**Comment by kristuff** [comment]
I admit that my regex is way too simplistic.

Your suggested regex and tests look good, but I still see cases the regex could let pass names containing certain allowed characters (for example {).

I will take a closer look in a few days, to be sure not to break running apps, then will change it and update the CLI app accordingly.

**Comment by kristuff** [comment]
I finally updated with an improved version of your simplified email pattern. 

```php
 $emailPattern   = "/\b[A-Z0-9!#$%&'*`\/?^{|}~=+_.-]+@[A-Z0-9.-]+\b/i";
```
Still not fully RFC compliant, but should handle most of cases, and allows using `@` in custom message.

Thank you to pointed out the case of local addresses, and the tip with word boundary operator. 👍
